#!/usr/bin/env node
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const CSS_PATH = join(ROOT, "src/app/globals.css");
const OUT_DIR = join(ROOT, "public/tokens");

const THEMES = ["tron", "ares", "clu", "athena", "aphrodite", "poseidon"];

function extractBlock(css, theme) {
  // Match selectors like `[data-theme="X"]` possibly combined with `:root,`.
  // We find the first `{` after the selector match, then balance braces.
  const selectorRegex = new RegExp(
    `(?:^|\\n)(?:[^{}]*?\\[data-theme="${theme}"\\][^{}]*?)\\{`,
    "m"
  );
  const match = selectorRegex.exec(css);
  if (!match) return null;

  const start = match.index + match[0].length;
  let depth = 1;
  let i = start;
  while (i < css.length && depth > 0) {
    const ch = css[i];
    if (ch === "{") depth++;
    else if (ch === "}") depth--;
    if (depth === 0) break;
    i++;
  }
  return css.slice(start, i).trim();
}

function parseVars(body) {
  const vars = {};
  const lines = body.split("\n");
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith("/*") || line.startsWith("*")) continue;
    const m = /^(--[\w-]+)\s*:\s*([^;]+);?$/.exec(line);
    if (!m) continue;
    vars[m[1]] = m[2].trim();
  }
  return vars;
}

async function ensureDir(path) {
  await mkdir(path, { recursive: true });
}

async function main() {
  const css = await readFile(CSS_PATH, "utf8");
  await ensureDir(OUT_DIR);

  const manifest = {
    name: "thegridcn",
    generatedAt: new Date().toISOString(),
    themes: [],
  };

  for (const theme of THEMES) {
    const body = extractBlock(css, theme);
    if (!body) {
      console.warn(`[tokens] theme "${theme}" not found in CSS`);
      continue;
    }

    const selector =
      theme === "tron" ? `:root,\n[data-theme="tron"]` : `[data-theme="${theme}"]`;
    const cssOut = `/* ${theme} · generated by scripts/export-tokens.mjs */\n${selector} {\n${body
      .split("\n")
      .map((l) => (l.trim() ? `  ${l.trim()}` : ""))
      .join("\n")}\n}\n`;

    const vars = parseVars(body);
    const jsonOut = {
      name: theme,
      selector: `[data-theme="${theme}"]`,
      vars,
    };

    const cssPath = join(OUT_DIR, `${theme}.css`);
    const jsonPath = join(OUT_DIR, `${theme}.json`);
    await writeFile(cssPath, cssOut, "utf8");
    await writeFile(jsonPath, JSON.stringify(jsonOut, null, 2) + "\n", "utf8");

    manifest.themes.push({
      name: theme,
      css: `/tokens/${theme}.css`,
      json: `/tokens/${theme}.json`,
      varCount: Object.keys(vars).length,
    });
    console.log(`[tokens] ${theme}: ${Object.keys(vars).length} vars`);
  }

  const indexPath = join(OUT_DIR, "index.json");
  await writeFile(indexPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");
  console.log(`[tokens] wrote ${indexPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
