#!/usr/bin/env tsx
/**
 * Auto-registry script for shadcn UI components
 * Scans components/ui directory and updates the registry
 */

import { writeFile, readFile } from "fs/promises"
import { join } from "path"
import { generateRegistryIndex, generateShadcnRegistry } from "../src/registry/scanner"

async function loadComponentsJson() {
  const content = await readFile(join(process.cwd(), "components.json"), "utf-8")
  return JSON.parse(content)
}

async function updateRegistry() {
  console.log("🔍 Scanning components...")

  try {
    // Load current components.json
    const componentsJson = await loadComponentsJson()

    // Generate registry entries
    const registryIndex = await generateRegistryIndex()

    // Update components.json with registry
    const updatedComponentsJson = {
      ...componentsJson,
      registries: {
        ...(componentsJson.registries || {}),
        "https://ui.shadcn.com": {
          name: "shadcn/ui",
          url: "https://ui.shadcn.com",
          registry: registryIndex,
        },
      },
    }

    // Write updated components.json
    await writeFile(
      join(process.cwd(), "components.json"),
      JSON.stringify(updatedComponentsJson, null, 2) + "\n",
      "utf-8"
    )

    // Generate TypeScript registry index
    const registryIndexContent = `// Auto-generated registry index
// This file is automatically generated by the registry scanner
// Run \`pnpm registry:update\` to regenerate

import type { ComponentRegistryEntry } from "./scanner"

export const registry: Record<string, ComponentRegistryEntry> = ${JSON.stringify(
      registryIndex,
      null,
      2
    )} as Record<string, ComponentRegistryEntry>

export function getRegistryEntry(name: string): ComponentRegistryEntry | undefined {
  return registry[name]
}

export function getAllRegistryEntries(): ComponentRegistryEntry[] {
  return Object.values(registry)
}

export function getRegistryDependencies(name: string): string[] {
  const entry = registry[name]
  return entry?.registryDependencies || []
}
`

    await writeFile(
      join(process.cwd(), "src/registry/index.ts"),
      registryIndexContent,
      "utf-8"
    )

    // Generate shadcn UI registry.json format
    // Try to get homepage from package.json or use default
    let homepage: string | undefined
    try {
      const packageJson = JSON.parse(
        await readFile(join(process.cwd(), "package.json"), "utf-8")
      )
      homepage =
        packageJson.homepage ||
        (packageJson.repository?.url
          ? packageJson.repository.url.replace(/\.git$/, "")
          : undefined) ||
        "https://github.com/educlopez/thegridcn-ui"
    } catch {
      homepage = "https://github.com/educlopez/thegridcn-ui"
    }

    const shadcnRegistry = await generateShadcnRegistry(undefined, {
      name: "thegridcn",
      homepage,
    })

    await writeFile(
      join(process.cwd(), "registry.json"),
      JSON.stringify(shadcnRegistry, null, 2) + "\n",
      "utf-8"
    )

    const componentCount = Object.keys(registryIndex).length
    console.log(`✅ Registry updated successfully!`)
    console.log(`   Found ${componentCount} components`)
    console.log(`   Updated components.json`)
    console.log(`   Updated src/registry/index.ts`)
    console.log(`   Updated registry.json`)
  } catch (error) {
    console.error("❌ Failed to update registry:", error)
    process.exit(1)
  }
}

updateRegistry()
